# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: gp open Hospital_Readmission_Cancer.ipynb

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
#ports:
#  - port: 3000
#    onOpen: open-preview
